"""Init

Revision ID: 1b35cc69d3e1
Revises: 61962eec31ce
Create Date: 2023-04-24 10:42:51.754580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b35cc69d3e1'
down_revision = '61962eec31ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
